# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/source directory
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Set the version of Python and requirements
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      # Install the package itself to make autodoc work
      - pip install .

# Install Python dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
