"""Type stubs for frequency_severity module."""

from __future__ import annotations

import typing as t
from collections.abc import Callable

import numpy as np
import numpy.typing as npt

from . import distributions
from .couplings import ProteusStochasticVariable
from .stochastic_scalar import StochasticScalar

ReductionOperation = t.Callable[
    [
        npt.NDArray[np.floating],
        npt.NDArray[np.int64],
        npt.NDArray[np.number[t.Any]],
    ],
    None,
]

ArrayTransform = t.Callable[
    [npt.NDArray[np.number[t.Any]]],
    npt.NDArray[np.number[t.Any]],
]

def _get_sims_of_events(
    n_events_by_sim: npt.NDArray[np.int64],
) -> npt.NDArray[np.int64]: ...

class FrequencySeverityModel:
    freq_dist: distributions.DistributionBase
    sev_dist: distributions.DistributionBase
    def __init__(
        self,
        freq_dist: distributions.DistributionBase,
        sev_dist: distributions.DistributionBase,
    ) -> None: ...
    def generate(
        self,
        n_sims: int | None = None,
        rng: np.random.Generator = ...,
    ) -> FreqSevSims: ...

class FreqSevSims(ProteusStochasticVariable):
    n_sims: int  # type: ignore[reportIncompatibleVariableOverride]
    sim_index: npt.NDArray[t.Any]
    def __init__(
        self,
        sim_index: np.ndarray | list[int],
        values: np.ndarray | list[float | int],
        n_sims: int,
    ) -> None: ...
    def __str__(self) -> str: ...
    def __getitem__(self, sim_index: int) -> StochasticScalar: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> t.Iterator[StochasticScalar]: ...
    def __repr__(self) -> str: ...

    # Arithmetic operators
    def __add__(self, other: t.Any) -> FreqSevSims: ...
    def __radd__(self, other: t.Any) -> FreqSevSims: ...
    def __sub__(self, other: t.Any) -> FreqSevSims: ...
    def __rsub__(self, other: t.Any) -> FreqSevSims: ...
    def __mul__(self, other: t.Any) -> FreqSevSims: ...
    def __rmul__(self, other: t.Any) -> FreqSevSims: ...
    def __truediv__(self, other: t.Any) -> FreqSevSims: ...
    def __rtruediv__(self, other: t.Any) -> FreqSevSims: ...
    def __pow__(self, other: t.Any) -> FreqSevSims: ...
    def __rpow__(self, other: t.Any) -> FreqSevSims: ...
    def __floordiv__(self, other: t.Any) -> FreqSevSims: ...
    def __rfloordiv__(self, other: t.Any) -> FreqSevSims: ...
    def __mod__(self, other: t.Any) -> FreqSevSims: ...
    def __rmod__(self, other: t.Any) -> FreqSevSims: ...

    # Array protocol
    def __array_ufunc__(
        self,
        ufunc: np.ufunc,
        method: str,
        *inputs: t.Any,
        **kwargs: t.Any,
    ) -> FreqSevSims: ...
    def __array_function__(
        self,
        func: Callable[..., t.Any],
        types: t.Any,
        args: t.Any,
        kwargs: t.Any,
    ) -> np.number[t.Any] | FreqSevSims: ...

    # Public methods
    def aggregate(self) -> StochasticScalar: ...
    def occurrence(self) -> StochasticScalar: ...
    def deep_copy(self) -> FreqSevSims: ...
    def copy(self) -> FreqSevSims: ...
    def apply(self, func: ArrayTransform) -> FreqSevSims: ...
    def upsample(self, n_sims: int) -> FreqSevSims: ...
    def _is_compatible(self, other: ProteusCompatibleTypes) -> bool: ...
    def _reorder_sims(self, new_order: t.Sequence[int]) -> None: ...
    def _reduce_over_events(
        self, operation: ReductionOperation
    ) -> StochasticScalar: ...
    def _extract_array_for_ufunc(self, x: t.Any) -> npt.NDArray[t.Any]: ...

ProteusCompatibleTypes = (
    FreqSevSims | StochasticScalar | int | float | npt.NDArray[t.Any]
)
