"""Type stubs for couplings module."""

from __future__ import annotations

import typing as t
import weakref
from abc import ABC

import numpy as np
import numpy.typing as npt
from numpy.lib.mixins import NDArrayOperatorsMixin

from ._compat import Self

class CouplingGroup:
    _refs: weakref.WeakValueDictionary[int, ProteusStochasticVariable]
    def __init__(self, variable: ProteusStochasticVariable) -> None: ...
    def add(self, obj: ProteusStochasticVariable) -> None: ...
    def discard(self, obj: ProteusStochasticVariable) -> None: ...
    def __contains__(self, obj: ProteusStochasticVariable) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> t.Iterator[ProteusStochasticVariable]: ...
    def merge(self, other: CouplingGroup) -> None: ...

class ProteusStochasticVariable(
    NDArrayOperatorsMixin,
    ABC,
):
    n_sims: int | None
    values: npt.NDArray[t.Any]
    coupled_variable_group: CouplingGroup
    _uid: int
    def __init__(self) -> None: ...
    def __array__(self, dtype: t.Any = None) -> npt.NDArray[t.Any]: ...
    # Comparison operators
    def __gt__(self, other: t.Any) -> Self: ...
    def __ge__(self, other: t.Any) -> Self: ...
    def __lt__(self, other: t.Any) -> Self: ...
    def __le__(self, other: t.Any) -> Self: ...
    def __eq__(self, other: t.Any) -> Self: ...  # type: ignore[override]
    def __ne__(self, other: t.Any) -> Self: ...  # type: ignore[override]
    # Divmod
    def __divmod__(self, other: t.Any) -> tuple[Self, Self]: ...
    def __rdivmod__(self, other: t.Any) -> tuple[Self, Self]: ...
    # Unary operators
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def __round__(self, ndigits: int | None = None) -> Self: ...
    def __floor__(self) -> Self: ...
    def __ceil__(self) -> Self: ...
    def __trunc__(self) -> Self: ...
    __hash__: None  # type: ignore[assignment]
    def __bool__(self) -> bool: ...
    def __array_function__(
        self,
        func: t.Any,
        types: tuple[type, ...],
        args: tuple[t.Any, ...],
        kwargs: dict[str, t.Any],
    ) -> t.Any: ...
    # Public methods
    def upsample(self, n_sims: int) -> Self: ...
    def astype(self, dtype: np.dtype[t.Any] | type[t.Any]) -> npt.NDArray[t.Any]: ...
    def any(self) -> bool: ...
    def all(self) -> bool: ...
    def _reorder_sims(self, new_order: t.Sequence[int]) -> None: ...
