"""Type stubs for stochastic_scalar module."""

from __future__ import annotations

import typing as t

import numpy as np
import numpy.typing as npt

from ._compat import Self
from .couplings import CouplingGroup, ProteusStochasticVariable
from .frequency_severity import FreqSevSims
from .stats import NumberOrList
from .types import Numeric, NumericLike, ScipyNumeric

V = t.TypeVar("V", bound="NumberOrList")

class StochasticScalar(ProteusStochasticVariable):
    coupled_variable_group: CouplingGroup
    n_sims: int  # type: ignore[reportIncompatibleVariableOverride]
    values: npt.NDArray[t.Any]  # Override to ensure proper type resolution
    def __init__(self, values: npt.ArrayLike) -> None: ...
    def __repr__(self) -> str: ...

    # Arithmetic: FreqSevSims overload + Any fallback
    @t.overload
    def __add__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __add__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __radd__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __radd__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __sub__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __sub__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rsub__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rsub__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __mul__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __mul__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rmul__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rmul__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __truediv__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __truediv__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rtruediv__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rtruediv__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __pow__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __pow__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rpow__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rpow__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __floordiv__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __floordiv__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rfloordiv__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rfloordiv__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __mod__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __mod__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __rmod__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __rmod__(self, other: t.Any) -> StochasticScalar: ...

    # Comparison: FreqSevSims overload + Any fallback
    @t.overload
    def __ge__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __ge__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __le__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __le__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __gt__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __gt__(self, other: t.Any) -> StochasticScalar: ...
    @t.overload
    def __lt__(  # type: ignore[reportOverlappingOverload]
        self, other: FreqSevSims
    ) -> FreqSevSims: ...
    @t.overload
    def __lt__(self, other: t.Any) -> StochasticScalar: ...

    # Array protocol
    def __array_ufunc__(
        self,
        ufunc: t.Any,
        method: str,
        *inputs: t.Any,
        **kwargs: t.Any,
    ) -> StochasticScalar: ...
    def __array_function__(
        self,
        func: t.Callable[..., t.Any],
        types: t.Any,
        args: t.Any,
        kwargs: t.Any,
    ) -> np.number[t.Any] | StochasticScalar: ...
    def __array__(self, dtype: t.Any = None) -> npt.NDArray[t.Any]: ...
    def __getitem__(self, index: ScipyNumeric | StochasticScalar) -> t.Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> t.Iterator[NumericLike]: ...

    # Properties
    @property
    def ranks(self) -> StochasticScalar: ...

    # Public methods
    def tolist(self) -> list[Numeric]: ...
    def mean(self) -> float: ...
    def sum(self) -> float: ...
    def std(self) -> float: ...
    def percentile(self, p: V) -> V: ...
    def tvar(self, p: V) -> V: ...
    def upsample(self, n_sims: int) -> Self: ...
    def show_histogram(self, title: str | None = None) -> None: ...
    def show_cdf(self, title: str | None = None) -> None: ...
    def _reorder_sims(self, new_order: t.Sequence[int]) -> None: ...
    def _wrap_result_with_coupling(self, result_array: t.Any, inputs: tuple[t.Any, ...]) -> StochasticScalar: ...
