"""Mirror package for backward compatibility.

This package (proteus-actuarial-library) is now a mirror of the renamed
proteusllp-actuarial-library package. All functionality is re-exported
from the main package.

For new projects, please use proteusllp-actuarial-library directly.
"""

from pal import *  # noqa: F401, F403

# Version is auto-generated by setuptools-scm
try:
    from proteus.__version__ import version as __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
